# Generated by Django 2.2.12 on 2020-05-05 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=1, verbose_name='User type')),
                ('classname', models.CharField(choices=[('J_I', 'Junior infant'), ('S_I', 'Senior infant'), ('1ST', '1st class'), ('2ND', '2nd class'), ('3RD', '3rd class'), ('4TH', '4th class'), ('5TH', '5th class'), ('6TH', '6th class')], max_length=3, verbose_name='Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
