# Generated by Django 3.0.6 on 2020-05-19 16:27

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200507_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentupload',
            name='content',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='', verbose_name='Upload content'),
        ),
    ]
