# Generated by Django 3.0.6 on 2020-05-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200519_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentupload',
            old_name='date',
            new_name='upload_date',
        ),
    ]
