# Generated by Django 3.0.6 on 2020-06-04 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200519_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentupload',
            name='title',
        ),
        migrations.AddField(
            model_name='contentupload',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
