# Generated by Django 3.0.6 on 2020-06-05 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200605_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
